### ISSUE TITLE
rolling and main branches are not in sync

### ISSUE THREAD

**Issue by esteve** [autowarefoundation/autoware_utils#7]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Same as https://github.com/autowarefoundation/autoware_adapi_msgs/issues/56

### Expected behavior

Same as https://github.com/autowarefoundation/autoware_adapi_msgs/issues/56

### Actual behavior

Same as https://github.com/autowarefoundation/autoware_adapi_msgs/issues/56

### Steps to reproduce

Same as https://github.com/autowarefoundation/autoware_adapi_msgs/issues/56

**Comment by esteve** [comment]
@isamu-takagi could you do the same (rebase main on top of rolling and force-push) as https://github.com/autowarefoundation/autoware_adapi_msgs/issues/56 for this repository when you have a moment? Thanks.

**Comment by isamu-takagi** [comment]
@esteve I don't have admin access for this repository.
@youtalk Do you have it?
